"""Export a checkpoint as a self-contained `solution/` folder the eval grader can run.

The grader mounts solution/ read-only with solve.py's directory on sys.path, in a container with
robobench + torch but not this package or rsl_rl. So the folder carries: solve.py (generic loop), policy.pt
(TorchScript actor + obs normalizer, deterministic), a copy of the torch-only parts of robobench_rl (obs
rule, the env base class, tasks/) and env.json (task_env name, config, horizon) — solve()
ATTACHES the training-time task env to the graded env, so observation and action processing are identical."""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import torch

SOLVE_TEMPLATE = '''"""RL policy solution — generated by rl/robobench_rl/export.py; nothing here is task-specific."""
import json
import sys
from pathlib import Path

import torch

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from robobench_rl.tasks import load_task_env_cls  # noqa: E402  (copied, torch-only)

META = json.loads((HERE / "env.json").read_text())


def solve(env) -> None:
    # attach the training-time task env to the graded env: same setup, observation and action processing
    task_env = load_task_env_cls(META.get("task_env"))(META["cfg"], env=env)
    if task_env.num_obs != META["num_obs"] or task_env.num_actions != META["num_actions"]:
        raise RuntimeError(f"obs/action dims {task_env.num_obs}/{task_env.num_actions} != trained "
                           f"{META['num_obs']}/{META['num_actions']}")
    policy = torch.jit.load(str(HERE / "policy.pt"), map_location=str(env.device)).eval()
    with torch.no_grad():
        for _ in range(int(META["max_episode_length"])):
            env.step(task_env.process_actions(policy(task_env.compute_obs())))
'''


class _Actor(torch.nn.Module):
    def __init__(self, normalizer, actor) -> None:
        super().__init__()
        self.normalizer, self.actor = normalizer, actor

    def forward(self, obs):
        return self.actor(self.normalizer(obs))


class _MLPActor(torch.nn.Module):
    """Tensor-only deterministic wrapper for an RSL-RL 5 MLP actor."""

    def __init__(self, normalizer, mlp) -> None:
        super().__init__()
        self.normalizer, self.mlp = normalizer, mlp

    def forward(self, obs):
        return self.mlp(self.normalizer(obs))


def export_solution(run_dir: str | Path, checkpoint: str | Path, out_dir: str | Path) -> Path:
    from tensordict import TensorDict

    run_dir, checkpoint, out_dir = Path(run_dir), Path(checkpoint), Path(out_dir)
    meta = json.loads((run_dir / "env.json").read_text())
    ckpt = torch.load(checkpoint, map_location="cpu", weights_only=False)
    n_obs = int(meta["num_obs"])
    obs = TensorDict({"policy": torch.zeros(1, n_obs), "critic": torch.zeros(1, n_obs)}, batch_size=[1])
    pol = dict(meta["cfg"]["ppo"]["policy"])
    if "actor_state_dict" in ckpt:
        from rsl_rl.models import MLPModel

        actor = MLPModel(
            obs,
            {"actor": ["policy"]},
            "actor",
            int(meta["num_actions"]),
            hidden_dims=pol["actor_hidden_dims"],
            activation=pol.get("activation", "elu"),
            obs_normalization=pol.get("actor_obs_normalization", False),
            distribution_cfg={
                "class_name": "GaussianDistribution",
                "init_std": pol.get("init_noise_std", 1.0),
                "std_type": pol.get("noise_std_type", "scalar"),
            },
        )
        actor.load_state_dict(ckpt["actor_state_dict"])
        actor.eval()
        actor = _MLPActor(actor.obs_normalizer, actor.mlp).eval()
    else:
        from rsl_rl.modules import ActorCritic

        sd = ckpt["model_state_dict"]
        n_obs = int(sd[next(k for k in sd if k.startswith("actor.") and k.endswith("weight"))].shape[1])
        pol.pop("class_name", None)
        ac = ActorCritic(obs, meta["cfg"]["ppo"]["obs_groups"], int(meta["num_actions"]), **pol)
        ac.load_state_dict(sd)
        ac.eval()
        actor = _Actor(ac.actor_obs_normalizer, ac.actor).eval()
    out_dir.mkdir(parents=True, exist_ok=True)
    with torch.no_grad():
        scripted = torch.jit.trace(actor, torch.zeros(1, n_obs))
        x = torch.randn(4, n_obs)
        if not torch.allclose(scripted(x), actor(x), atol=1e-5):
            raise RuntimeError("traced actor disagrees with eager actor")
    scripted.save(str(out_dir / "policy.pt"))
    pkg_src, pkg_dst = Path(__file__).parent, out_dir / "robobench_rl"  # the torch-only runtime pieces
    if pkg_dst.exists():
        shutil.rmtree(pkg_dst)
    pkg_dst.mkdir()
    (pkg_dst / "__init__.py").write_text('"""runtime copy for grading (obs rule, tasks/)"""\n')
    for f in ("obs.py", "vec_env.py"):  # vec_env imports rsl_rl only if present
        shutil.copy(pkg_src / f, pkg_dst / f)
    shutil.copytree(pkg_src / "tasks", pkg_dst / "tasks", ignore=shutil.ignore_patterns("__pycache__"))
    (out_dir / "solve.py").write_text(SOLVE_TEMPLATE)
    meta_out = {k: meta[k] for k in ("preset", "task_env", "num_actions", "step_dt", "max_episode_length", "cfg")}
    meta_out.update(num_obs=n_obs, checkpoint=checkpoint.name, train_iteration=int(ckpt.get("iter", -1)), run_dir=str(run_dir))
    (out_dir / "env.json").write_text(json.dumps(meta_out, indent=2))
    return out_dir
